# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import rideshare_pb2 as proto_dot_rideshare__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/rideshare_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DriverServiceStub(object):
    """2. Define the Services (The API endpoints)

    Service 1: The Driver app talks to this
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateLocation = channel.unary_unary(
                '/rideshare.DriverService/UpdateLocation',
                request_serializer=proto_dot_rideshare__pb2.Driver.SerializeToString,
                response_deserializer=proto_dot_rideshare__pb2.LocationAck.FromString,
                _registered_method=True)


class DriverServiceServicer(object):
    """2. Define the Services (The API endpoints)

    Service 1: The Driver app talks to this
    """

    def UpdateLocation(self, request, context):
        """Drivers send a continuous stream of location updates
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DriverServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateLocation': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateLocation,
                    request_deserializer=proto_dot_rideshare__pb2.Driver.FromString,
                    response_serializer=proto_dot_rideshare__pb2.LocationAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rideshare.DriverService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rideshare.DriverService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DriverService(object):
    """2. Define the Services (The API endpoints)

    Service 1: The Driver app talks to this
    """

    @staticmethod
    def UpdateLocation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rideshare.DriverService/UpdateLocation',
            proto_dot_rideshare__pb2.Driver.SerializeToString,
            proto_dot_rideshare__pb2.LocationAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class RiderServiceStub(object):
    """Service 2: The Rider app talks to this
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetNearestDrivers = channel.unary_unary(
                '/rideshare.RiderService/GetNearestDrivers',
                request_serializer=proto_dot_rideshare__pb2.RiderRequest.SerializeToString,
                response_deserializer=proto_dot_rideshare__pb2.NearbyDriversResponse.FromString,
                _registered_method=True)


class RiderServiceServicer(object):
    """Service 2: The Rider app talks to this
    """

    def GetNearestDrivers(self, request, context):
        """Riders send one request, get one list of drivers back
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RiderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetNearestDrivers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNearestDrivers,
                    request_deserializer=proto_dot_rideshare__pb2.RiderRequest.FromString,
                    response_serializer=proto_dot_rideshare__pb2.NearbyDriversResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rideshare.RiderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rideshare.RiderService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RiderService(object):
    """Service 2: The Rider app talks to this
    """

    @staticmethod
    def GetNearestDrivers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rideshare.RiderService/GetNearestDrivers',
            proto_dot_rideshare__pb2.RiderRequest.SerializeToString,
            proto_dot_rideshare__pb2.NearbyDriversResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)