# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/rideshare.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/rideshare.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15proto/rideshare.proto\x12\trideshare\"/\n\x08Location\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\"R\n\x06\x44river\x12\x11\n\tdriver_id\x18\x01 \x01(\t\x12%\n\x08location\x18\x02 \x01(\x0b\x32\x13.rideshare.Location\x12\x0e\n\x06status\x18\x03 \x01(\t\"]\n\x0cRiderRequest\x12\x10\n\x08rider_id\x18\x01 \x01(\t\x12%\n\x08location\x18\x02 \x01(\x0b\x32\x13.rideshare.Location\x12\x14\n\x0cradius_miles\x18\x03 \x01(\x05\";\n\x15NearbyDriversResponse\x12\"\n\x07\x64rivers\x18\x01 \x03(\x0b\x32\x11.rideshare.Driver\"/\n\x0bLocationAck\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2N\n\rDriverService\x12=\n\x0eUpdateLocation\x12\x11.rideshare.Driver\x1a\x16.rideshare.LocationAck\"\x00\x32`\n\x0cRiderService\x12P\n\x11GetNearestDrivers\x12\x17.rideshare.RiderRequest\x1a .rideshare.NearbyDriversResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.rideshare_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOCATION']._serialized_start=36
  _globals['_LOCATION']._serialized_end=83
  _globals['_DRIVER']._serialized_start=85
  _globals['_DRIVER']._serialized_end=167
  _globals['_RIDERREQUEST']._serialized_start=169
  _globals['_RIDERREQUEST']._serialized_end=262
  _globals['_NEARBYDRIVERSRESPONSE']._serialized_start=264
  _globals['_NEARBYDRIVERSRESPONSE']._serialized_end=323
  _globals['_LOCATIONACK']._serialized_start=325
  _globals['_LOCATIONACK']._serialized_end=372
  _globals['_DRIVERSERVICE']._serialized_start=374
  _globals['_DRIVERSERVICE']._serialized_end=452
  _globals['_RIDERSERVICE']._serialized_start=454
  _globals['_RIDERSERVICE']._serialized_end=550
# @@protoc_insertion_point(module_scope)
